version: '2'

services:
  prometheus:
    build: ./prometheus
    image: devops/prometheus
    environment:
      PROMETHEUS_SERVER_VERSION: 1.3.1
    volumes:
      - ~/docker/volumes/prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    build: ./grafana
    image: devops/grafana
    ports:
      - "3000:3000"

  jenkins:
    image: jenkins
    ports:
      - "8060:8080"
      - "50000:50000"
    volumes:
      - ~/docker/volumes/jenkins:/var/jenkins_home

  cadvisor:
    image: google/cadvisor
    ports:
      - "9080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  sitemetrics-exporter:
    build: ./sitemetrics-exporter
    image: devops/sitemetrics-exporter
    ports:
      - "9149:9149"

  node-exporter:
    build: ./node-exporter
    image: devops/node-exporter
    ports:
      - "4000:4000"
      - "9100:9100"
