kind: BuildConfig
apiVersion: v1
metadata:
  name: prometheus
spec:
  triggers: []
  source:
    type: Git
    git:
      uri: https://ghe.adp.allianz/AZD-DevOps/monitoring.git
      ref: master
    secrets:
    - destinationDir: ./monitoring
      secret:
        name: npmrc-lazy-proxy
    contextDir: services
    sourceSecret:
      name: ghe-credentials
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: prometheus/Dockerfile
  resources:
    limits:
      cpu: 300m
      memory: 1Gi
    requests:
      cpu: 150m
      memory: 512Mi
  output:
    to:
      kind: "ImageStreamTag"
      name: "prometheus"
