# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['monitoring_node-exporter_1:9100']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['monitoring_cadvisor_1:8080']

  - job_name: 'sitemetrics_google_de'
    scrape_interval: 20s
    metrics_path: "/"
    params:
      'url': ['http://google.de']
    static_configs:
      - targets: ['monitoring_sitemetrics-exporter_1:9149']

  - job_name: 'sitemetrics_bluebird_service'
    scrape_interval: 120s
    metrics_path: "/"
    params:
      'url': ['https://api-test.allianz.de/bluebird-api/service']
    static_configs:
      - targets: ['monitoring_sitemetrics-exporter_1:9149']

  - job_name: 'jenkins_metrics'
    scrape_interval: 120s
    metrics_path: "/prometheus"
    static_configs:
      - targets: ['monitoring_jenkins_1:8060']
