# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'pcf-metrics-quotas'
    # Override the global default and scrape targets from this job every 1 seconds.
    scrape_interval: 10s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['adp-dashboard.apps.adp.allianz']

  # Example for scraping cadvisor metrics from oc. needs additional configuration for accessing the nodes. curling this replies with a json body saying forbidden for anonymous user
  - job_name: 'oc-node-metrics'
    scrape_interval: 15s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['compute-node01.os-test.adp.allianz:10250']


  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']


  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:9080']


  - job_name: 'sitemetrics_google_de'
    scrape_interval: 20s
    metrics_path: "/"
    params:
      'url': ['http://google.de']
    static_configs:
      - targets: ['phantomas-exporter:9149']


  - job_name: 'sitemetrics_bluebird_service'
    scrape_interval: 120s
    metrics_path: "/"
    params:
      'url': ['https://api-test.allianz.de/bluebird-api/service']
    static_configs:
      - targets: ['phantomas-exporter:9149']


  - job_name: 'jenkins_metrics'
    scrape_interval: 120s
    metrics_path: "/prometheus"
    static_configs:
      - targets: ['jenkins:8060']
